name: np8080
description: A web based Text editor app built with Angular Dart.
version: 0.0.22
homepage: https://github.com/daftspaniel/np8080
author: Davy Mitchell <daftspaniel@gmail.com>
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  angular2: ^3.1.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.23+1
  pwa: ^0.1.7
  stringprocess: ^0.0.1
  minibus: ^0.0.1
  intl: ^0.15.1
transformers:
- angular2:
    angular2/transform/codegen:
        use_analyzer: true
    entry_points: web/main.dart
- dart_to_js_script_rewriter
