name: np8080
description: A web based Text editor built with Angular Dart.
version: 0.0.31
homepage: https://github.com/daftspaniel/np8080
author: Davy Mitchell <daftspaniel@gmail.com>
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
  angular: 5.0.0-alpha+13
  angular_compiler: 0.4.0-alpha+13
  angular_forms: 2.0.0-alpha+5
  test: ^0.12.23+1
  stringprocess: ^1.0.6
  minibus: ^0.0.3
  intl: ^0.15.1
  diff: ^0.1.1
  pwa: ^0.1.10
dev_dependencies:
  build_runner: ^0.8.1
  build_web_compilers: ^0.3.4+2
