name: np8080
description: A web based Text editor built with Angular Dart.
version: 0.0.29
homepage: https://github.com/daftspaniel/np8080
author: Davy Mitchell <daftspaniel@gmail.com>
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
  angular: 5.0.0-alpha+7
  angular_compiler: 0.4.0-alpha+7
  angular_forms: 1.0.1-alpha+7
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.23+1
  stringprocess: ^0.0.7
  minibus: ^0.0.3
  intl: ^0.15.1
  diff: ^0.1.1
  pwa: ^0.1.9
dev_dependencies:
  build_runner: ^0.7.0
  build_web_compilers: ^0.2.0