name: np8080
description: A web based Text editor app that uses AngularDart
version: 0.0.10
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular2: ^2.2.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  markdown: ^0.11.1
  test: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
