name: np8080
description: A web based Text editor built with Angular Dart.
version: 0.0.28
homepage: https://github.com/daftspaniel/np8080
author: Davy Mitchell <daftspaniel@gmail.com>
environment:
  sdk: '>=1.24.2 <2.0.0'
dependencies:
  angular: ^4.0.0
  angular_forms: ^0.1.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.23+1
  pwa: ^0.1.7
  stringprocess: ^0.0.7
  minibus: ^0.0.3
  intl: ^0.15.1
  diff: ^0.1.1
transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter